/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        boolean shouldFinish = false;
        Scanner scanner = new Scanner(System.in);
        int chosen = 0;
        int sum = 0;
        while (!shouldFinish) {
            chosen = 0;
            System.out.println("Ile kostek chcesz rzucić?(3-10)");
            chosen = scanner.nextInt();
            while (chosen <= 10 && chosen >= 3) {

                for (int i = 0; chosen > i; i++) {
                    int random = (int) (Math.random() * 6) + 1;
                    System.out.println("Kostka " + (i + 1) + ": " + random);
                    sum += random;
                }
                System.out.println("Liczba uzyskanych punktów: " + sum);
                chosen = 0;
                sum = 0;
                System.out.println("Jeszcze raz? (t/n)");
                String answer = scanner.next();
                shouldFinish = answer.equals("n") ? true : false;
            }

        }
        scanner.close();
    }
}
