name: Android CI - Dice Game

on:
  push:
    branches: ["main"]
    paths:
      - "Java/Mobile_Dice_App_Java/app/**"  # Only run when files in the Java/x/app folder change
  pull_request:
    branches: ["main"]
    paths:
      - "Java/Mobile_Dice_App_Java/app/**"  # Only run when files in the Java/x/app folder change
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build
